#!/usr/bin/env bash

pkgdir="$(dirname "$(realpath "$BASH_SOURCE")")"

BUBBLE_USERSCRIPT_DIRECTORY="$pkgdir/scripts"
[ "$DEBUG" = "0" ] || DEBUG=1

export BUBBLE_USERSCRIPT_DIRECTORY
export DEBUG

cfx --overload-modules \
    --binary "$HOME/.local/bin/firefox" \
    --pkgdir="$pkgdir" \
    --profiledir="$HOME/.mozilla/firefox/cfx" \
    run
